server:
  port: 8066
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://192.168.1.21:8761/eureka/
      prefer-ip-address: true
spring:
  application:
    name: spring-config-client  
  cloud:
    config:
      name: myapp-dev
      label: master
      discovery:
        enabled: true
        service-id: spring-config-server    
