server:
  port: 8066

spring:
  application:
    name: spring-config-client  
  cloud:
    config:
      name: myapp-dev
      label: master
      discovery:
        enabled: true
        service-id: spring-config-server    
